version: '3.5'
services:
 zabbix-server:
  image: zabbix/zabbix-server-mysql:alpine-6.0-latest
  restart: always
  ports:
   - "10051:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro 
#   - dbsocket:/var/run/mysqld/
   - ./data/zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
   - ./data/zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - ./data/zbx_env/var/lib/zabbix/dbscripts:/var/lib/zabbix/dbscripts:ro
   - ./data/zbx_env/var/lib/zabbix/export:/var/lib/zabbix/export:rw
   - ./data/zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ./data/zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ./data/zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
   - ./data/zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
   - snmptraps:/var/lib/zabbix/snmptraps:rw
  ulimits:
   nproc: 65535
   nofile:
    soft: 20000
    hard: 40000
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 1G
    reservations:
      cpus: '0.5'
      memory: 512M
  env_file:
   - ./env_vars/.env_db_mysql
   - ./env_vars/.env_srv
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
   - MYSQL_ROOT_USER
   - MYSQL_ROOT_PASSWORD
  depends_on:
   - mysql-server
  networks:
   zbx_net_backend:
     aliases:
      - zabbix-server
      - zabbix-server-mysql
      - zabbix-server-alpine-mysql
      - zabbix-server-mysql-alpine
   zbx_net_frontend:
  stop_grace_period: 30s
  sysctls:
   - net.ipv4.ip_local_port_range=1024 65000
   - net.ipv4.conf.all.accept_redirects=0
   - net.ipv4.conf.all.secure_redirects=0
   - net.ipv4.conf.all.send_redirects=0
  labels:
   com.zabbix.description: "Zabbix server with MySQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-server"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "alpine"

 zabbix-web-nginx-mysql:
  image: zabbix/zabbix-web-nginx-mysql:alpine-6.0-latest
  restart: always
  ports:
   - "4000:8080"
#   - "443:8443"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
#   - dbsocket:/var/run/mysqld/
   - ./data/zbx_env/etc/ssl/nginx:/etc/ssl/nginx:ro
   - ./data/zbx_env/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 512M
    reservations:
      cpus: '0.5'
      memory: 256M
  env_file:
   - ./env_vars/.env_db_mysql
   - ./env_vars/.env_web
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
#   - client-key.pem
#   - client-cert.pem
#   - root-ca.pem
  depends_on:
   - mysql-server
   - zabbix-server
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
   interval: 10s
   timeout: 5s
   retries: 3
   start_period: 30s
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-web-nginx-mysql
     - zabbix-web-nginx-alpine-mysql
     - zabbix-web-nginx-mysql-alpine
   zbx_net_frontend:
  stop_grace_period: 10s
  sysctls:
   - net.core.somaxconn=65535
  labels:
   com.zabbix.description: "Zabbix frontend on Nginx web-server with MySQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-frontend"
   com.zabbix.webserver: "nginx"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "alpine"

 zabbix-agent:
  image: zabbix/zabbix-agent:alpine-6.0-latest
  restart: always
  ports:
   - "10050:10050"
  volumes:
#   - /etc/localtime:/etc/localtime:ro
#   - /etc/timezone:/etc/timezone:ro
   - ./data/zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
   - ./data/zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
   - ./data/zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
   - ./data/zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
  deploy:
   resources:
    limits:
      cpus: '0.2'
      memory: 128M
    reservations:
      cpus: '0.1'
      memory: 64M
   mode: global
  env_file:
   - ./env_vars/.env_agent
  privileged: true
  pid: "host"
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-agent
     - zabbix-agent-passive
     - zabbix-agent-alpine
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix agent"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-agentd"
   com.zabbix.os: "alpine"

 zabbix-snmptraps:
  image: zabbix/zabbix-snmptraps:alpine-6.0-latest
  restart: always
  ports:
   - "162:1162/udp"
  volumes:
   - snmptraps:/var/lib/zabbix/snmptraps:rw
  deploy:
   resources:
    limits:
      cpus: '0.5'
      memory: 256M
    reservations:
      cpus: '0.25'
      memory: 128M
  networks:
   zbx_net_frontend:
    aliases:
     - zabbix-snmptraps
   zbx_net_backend:
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix snmptraps"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "snmptraps"
   com.zabbix.os: "alpine"

 zabbix-web-service:
  image: zabbix/zabbix-web-service:alpine-6.0-latest
  restart: always
  ports:
   - "10053:10053"
  volumes:
   - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
  security_opt:
   - seccomp:./env_vars/chrome_dp.json
  deploy:
   resources:
    limits:
      cpus: '0.5'
      memory: 512M
    reservations:
      cpus: '0.25'
      memory: 256M
  env_file:
   - ./env_vars/.env_web_service
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-web-service
     - zabbix-web-service-alpine
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix web service"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "web-service"
   com.zabbix.os: "alpine"

 mysql-server:
  image: mysql:8.0-oracle
  restart: always
  command:
   - mysqld
   - --character-set-server=utf8mb4
   - --collation-server=utf8mb4_bin
   - --skip-character-set-client-handshake
   - --default-authentication-plugin=mysql_native_password
#   - --require-secure-transport
#   - --ssl-ca=/run/secrets/root-ca.pem
#   - --ssl-cert=/run/secrets/server-cert.pem
#   - --ssl-key=/run/secrets/server-key.pem
  volumes:
   - ./data/zbx_env/var/lib/mysql:/var/lib/mysql:rw
#   - dbsocket:/var/run/mysqld/
  env_file:
   - ./env_vars/.env_db_mysql
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
   - MYSQL_ROOT_PASSWORD
#   - server-key.pem
#   - server-cert.pem
#   - root-ca.pem
  stop_grace_period: 1m
  networks:
   zbx_net_backend:
    aliases:
     - mysql-server
     - zabbix-database
     - mysql-database

 db_data_mysql:
  image: busybox
  volumes:
   - ./data/zbx_env/var/lib/mysql:/var/lib/mysql:rw

 postgres:
   image: "postgres"
   restart: always
   networks:
     - zbx_net_frontend
   ports:
     - 5432:5432
   environment:
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=admin
     - POSTGRES_DB=grafana
   volumes:
     - ./data/grafana_env/postgres/data:/var/lib/postgresql/data/
 grafana:
   image: grafana/grafana:latest
   restart: always
   user: "1000"
   depends_on:
     - redis
     - postgres
   networks:
     - zbx_net_frontend
   ports:
     - "4001:3000"
   volumes:
     - ./data/grafana_env/data:/var/lib/grafana
     - ./data/grafana_env/log:/var/log/grafana
   environment:
     GF_DATABASE_HOST: "postgres:5432"
     GF_DATABASE_TYPE: postgres
     GF_DATABASE_SSL_MODE: disable
     GF_AUTH_LOGIN_COOKIE_NAME: grafana_session
     GF_AUTH_LOGIN_MAXIMUM_INACTIVE_LIFETIME_DAYS: 7
     GF_AUTH_LOGIN_MAXIMUM_LIFETIME_DAYS: 30
     GF_AUTH_TOKEN_ROTATION_INTERVAL_MINUTES: 1440
#     GF_AUTH_LDAP_ENABLED: true
#     GF_AUTH_LDAP_CONFIG_FILE: /var/lib/grafana/ldap/ldap.toml
     GF_SESSION_PROVIDER: redis
     GF_SESSION_PROVIDER_CONFIG: "addr=redis:6379,pool_size=300,db=grafana,prefix=grafana"
     GF_SESSION_COOKIE_SECURE: "true"
     GF_PANELS_DISABLE_SANITIZE_HTML: "true"
     GF_LOG_LEVEL: debug
     GF_LOG_MODE: console
     GF_INSTALL_PLUGINS: alexanderzobnin-zabbix-app
     GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: alexanderzobnin-zabbix-app, alexanderzobnin-zabbix-datasource
     GF_SERVER_ROOT_URL: http://192.168.25.21:8081
   env_file:
     - ./env_vars/.env_grafana

 redis:
   image: redis:latest
   restart: always
   ports:
     - 6379:6379
   networks:
     - zbx_net_frontend
   environment:
     - ALLOW_EMPTY_PASSWORD=yes

 js7-db:
   image: mysql:8.0
   ports:
     - "3306:3306"
   command:
     - --default-authentication-plugin=mysql_native_password
     - --character-set-server=utf8mb4
     - --collation-server=utf8mb4_bin
     - --skip-character-set-client-handshake
   volumes:
     - ./data/js7_env/db_data:/var/lib/mysql
   networks:
     - js7network
   env_file:
     - ./env_vars/.env_js7db
   restart: "no"
 js7-joc-primary:
   depends_on:
     - js7-db
   image: "sosberlin/js7:joc-${JS7VERSION}"
   hostname: js7-joc-primary
   ports:
     - "4446:4446"
   volumes:
     - ./hibernate.cfg.xml:/var/sos-berlin.com/js7/joc/resources/joc/hibernate.cfg.xml
     - ./data/js7_env/js7-joc-primary-logs:/var/log/sos-berlin.com/js7/joc
   networks:
     - js7network
   env_file:
     - ./env_vars/.env_js7jocprimary
   restart: "no"

 js7-controller-primary:
    image: sosberlin/js7:controller-${JS7VERSION}
    hostname: js7-controller-primary
    networks:
      - js7network
    env_file:
      - ./env_vars/.env_js7controllerprimary
    restart: "no"

 js7-agent-primary:
    image: sosberlin/js7:agent-${JS7VERSION}
    hostname: js7-agent-primary
    networks:
      - js7network
    env_file:
      - ./env_vars/.env_js7agentprimary
    restart: "no"

networks:
  zbx_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
#      config:
#      - subnet: 172.16.238.0/24
  zbx_net_backend:
    driver: bridge 
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
#      config:
#      - subnet: 172.16.239.0/24
  js7network:
volumes:
  snmptraps:
#  dbsocket:

secrets:
  MYSQL_USER:
    file: ./env_vars/.MYSQL_USER
  MYSQL_PASSWORD:
    file: ./env_vars/.MYSQL_PASSWORD
  MYSQL_ROOT_USER:
    file: ./env_vars/.MYSQL_ROOT_USER
  MYSQL_ROOT_PASSWORD:
    file: ./env_vars/.MYSQL_ROOT_PASSWORD
#  client-key.pem:
#    file: ./env_vars/.ZBX_DB_KEY_FILE
#  client-cert.pem:
#    file: ./env_vars/.ZBX_DB_CERT_FILE
#  root-ca.pem:
#    file: ./env_vars/.ZBX_DB_CA_FILE
#  server-cert.pem:
#    file: ./env_vars/.DB_CERT_FILE
#  server-key.pem:
#    file: ./env_vars/.DB_KEY_FILE
